2020-12-07 08:33:57,757 INFO    MainThread:17096 [wandb_setup.py:_flush():70] setting env: {}
2020-12-07 08:33:57,757 INFO    MainThread:17096 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2020-12-07 08:33:57,758 INFO    MainThread:17096 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-07 08:33:57,758 INFO    MainThread:17096 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\ST200423\PycharmProjects\SVHM\SVHNClassifier-PyTorch-master\wandb\run-20201207_083357-15r5nf5m\logs\debug.log
2020-12-07 08:33:57,759 INFO    MainThread:17096 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\ST200423\PycharmProjects\SVHM\SVHNClassifier-PyTorch-master\wandb\run-20201207_083357-15r5nf5m\logs\debug-internal.log
2020-12-07 08:34:01,360 INFO    MainThread:17096 [wandb_run.py:_console_start():1218] atexit reg
2020-12-07 08:34:01,361 INFO    MainThread:17096 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-12-07 08:34:01,362 INFO    MainThread:17096 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-12-07 08:34:01,362 INFO    MainThread:17096 [wandb_run.py:_redirect():1132] Redirects installed.
2020-12-07 08:34:08,698 INFO    Dummy-4   :17096 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 255
2020-12-07 08:34:08,699 INFO    Dummy-4   :17096 [wandb_run.py:_restore():1160] restore
2020-12-07 08:34:08,702 INFO    Dummy-4   :17096 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "dc395c040b1e45898ce92713503a449c"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 521
      total_bytes: 521
    }
  }
}

2020-12-07 08:34:10,707 INFO    Dummy-4   :17096 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "0184d2e08a344fc5927eb601e6686c89"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 14901
      total_bytes: 14901
    }
  }
}

2020-12-07 08:34:12,713 INFO    Dummy-4   :17096 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "7d75135d1f2549368a0b25e5c26761b6"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 14901
      total_bytes: 14901
    }
  }
}

2020-12-07 08:34:13,827 INFO    Dummy-4   :17096 [wandb_run.py:_show_files():1517] logging synced files
2020-12-07 08:34:13,829 INFO    Dummy-4   :17096 [internal.py:handle_exit():138] Internal process exited
