2020-12-07 08:32:45,749 INFO    MainThread:24144 [wandb_setup.py:_flush():70] setting env: {}
2020-12-07 08:32:45,749 INFO    MainThread:24144 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2020-12-07 08:32:45,749 INFO    MainThread:24144 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-07 08:32:45,749 INFO    MainThread:24144 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\ST200423\PycharmProjects\SVHM\SVHNClassifier-PyTorch-master\wandb\run-20201207_083245-3bnhwi6l\logs\debug.log
2020-12-07 08:32:45,750 INFO    MainThread:24144 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\ST200423\PycharmProjects\SVHM\SVHNClassifier-PyTorch-master\wandb\run-20201207_083245-3bnhwi6l\logs\debug-internal.log
2020-12-07 08:32:49,340 INFO    MainThread:24144 [wandb_run.py:_console_start():1218] atexit reg
2020-12-07 08:32:49,342 INFO    MainThread:24144 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-12-07 08:32:49,342 INFO    MainThread:24144 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-12-07 08:32:49,342 INFO    MainThread:24144 [wandb_run.py:_redirect():1132] Redirects installed.
2020-12-07 08:33:01,304 INFO    Dummy-4   :24144 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 255
2020-12-07 08:33:01,304 INFO    Dummy-4   :24144 [wandb_run.py:_restore():1160] restore
2020-12-07 08:33:01,306 INFO    Dummy-4   :24144 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "15ba01d3b01a4bd2aa875c178ef70ec5"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 521
      total_bytes: 521
    }
  }
}

2020-12-07 08:33:03,311 INFO    Dummy-4   :24144 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "3aab2b60ac0347bbb82f6190073825b4"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 21481
      total_bytes: 21481
    }
  }
}

2020-12-07 08:33:05,318 INFO    Dummy-4   :24144 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "a3147e9b2424474b8e7387b333acf515"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 21481
      total_bytes: 21481
    }
  }
}

2020-12-07 08:33:06,391 INFO    Dummy-4   :24144 [wandb_run.py:_show_files():1517] logging synced files
2020-12-07 08:33:06,392 INFO    Dummy-4   :24144 [internal.py:handle_exit():138] Internal process exited
